### ISSUE TITLE
Will you update to Bootstrap 5?

### ISSUE THREAD

**Issue by mailinglist12** [RichDeBourke/simple-f3-multi-lang-site#1]
Bootstrap 5 is awesome. Use native JS and now support impresives icons.
Will you update this project to Bootstrap 5?

**Comment by RichDeBourke** [comment]
The primary purpose for this repository is to document using the _Fat-Free Framework_ to setup a multi-language site. When I created the repository in 2018 (before V5 was introduced), I used Bootstrap 4 as I like the Bootstrap front-end framework and it supports Internet Explorer (around 4% of the visitors to my production sites still use IE).

At some point, _I do plan to fork this repository_ and create a V5 version, but not in the near-term.

**Comment by RichDeBourke** [comment]
With the release of Bootstrap 5.3 with support for dark mode and Microsoft ending Internet Explorer, it was a good time to create a multi-language site utilizing F3 and Bootstrap 5.

The repository for the new configuration is at: [https://github.com/RichDeBourke/simple-f3-bootstrap-5-multi-lang-site](https://github.com/RichDeBourke/simple-f3-bootstrap-5-multi-lang-sitel)

**Comment by RichDeBourke** [comment]
With the release of Bootstrap 5.3 with support for dark mode and Microsoft ending Internet Explorer, it was a good time to create a multi-language site utilizing F3 and Bootstrap 5.

The repository for the new configuration is at: [https://github.com/RichDeBourke/simple-f3-bootstrap-5-multi-lang-site](https://github.com/RichDeBourke/simple-f3-bootstrap-5-multi-lang-site)
